---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/cp -v shared.css $DEPLOYPATH
    - /bin/cp -v index.html $DEPLOYPATH
    - /bin/cp -v styles.css $DEPLOYPATH
    - /bin/cp -v script.js $DEPLOYPATH
    - /bin/cp -v experiences/tvtracker/index.html $DEPLOYPATH/tvtracker.html
    - /bin/cp -v experiences/tvtracker/style.css $DEPLOYPATH/tvtracker.css
    - /bin/cp -v experiences/tvtracker/script.js $DEPLOYPATH/tvtracker.js
    - /bin/cp -v experiences/howsyourday/index.html $DEPLOYPATH/howsyourday.html
    - /bin/cp -v experiences/howsyourday/style.css $DEPLOYPATH/howsyourday.css
    - /bin/cp -v experiences/howsyourday/script.js $DEPLOYPATH/howsyourday.js
    - /bin/cp -v experiences/codecracker/index.html $DEPLOYPATH/codecracker.html
    - /bin/cp -v experiences/codecracker/style.css $DEPLOYPATH/codecracker.css
    - /bin/cp -v experiences/codecracker/script.js $DEPLOYPATH/codecracker.js
